#-----------------------------------------------------------------
# ______      _   _            _    _ _     _ _       _ _     _
# | ___ \    | | | |          | |  | | |   (_) |     | (_)   | |
# | |_/ / ___| |_| |_ ___ _ __| |  | | |__  _| |_ ___| |_ ___| |_
# | ___ \/ _ \ __| __/ _ \ '__| |/\| | '_ \| | __/ _ \ | / __| __|
# | |_/ /  __/ |_| ||  __/ |  \  /\  / | | | | ||  __/ | \__ \ |_
# \____/ \___|\__|\__\___|_|   \/  \/|_| |_|_|\__\___|_|_|___/\__|
#
#
#-----------------------------------------------------------------

# Language
language: en
# Currently only English (en) and Czech (cs) are supported

# Whitelist enabled or disabled
enabled: false
# By default whitelist is disabled
